<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ECommerce.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Modules/Catalog/ECommerce.Modules.Catalog.Api/ECommerce.Modules.Catalog.Api.csproj" />
    <ProjectReference Include="../Modules/Catalog/ECommerce.Modules.Catalog.Infrastructure/ECommerce.Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Orders/ECommerce.Modules.Orders.Api/ECommerce.Modules.Orders.Api.csproj" />
    <ProjectReference Include="../Modules/Orders/ECommerce.Modules.Orders.Infrastructure/ECommerce.Modules.Orders.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Payments/ECommerce.Modules.Payments.Api/ECommerce.Modules.Payments.Api.csproj" />
    <ProjectReference Include="../Modules/Payments/ECommerce.Modules.Payments.Infrastructure/ECommerce.Modules.Payments.Infrastructure.csproj" />
    <ProjectReference Include="../ECommerce.SharedKernel/ECommerce.SharedKernel.csproj" />
  </ItemGroup>

</Project>
