<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ECommerce.Modules.Payments.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ECommerce.Modules.Payments.Domain/ECommerce.Modules.Payments.Domain.csproj" />
    <ProjectReference Include="../ECommerce.Modules.Payments.Application/ECommerce.Modules.Payments.Application.csproj" />
    <ProjectReference Include="../../../ECommerce.SharedKernel/ECommerce.SharedKernel.csproj" />
  </ItemGroup>
</Project>
