using FluentMigrator;

namespace ECommerce.Database.Migrator.Seeds;

[Migration(103)]
public class M103_SeedAdminUser : Migration
{
    public override void Up()
    {
        // Create identity schema and users table
        Execute.Sql("CREATE SCHEMA IF NOT EXISTS identity;");

        Execute.Sql(@"
            CREATE TABLE IF NOT EXISTS identity.users (
                id UUID PRIMARY KEY,
                email VARCHAR(256) NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                role VARCHAR(50) NOT NULL DEFAULT 'User',
                phone VARCHAR(20),
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                last_login_at TIMESTAMP WITH TIME ZONE,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );
        ");

        // Seed admin user
        // Password: Admin@123 (hashed with PBKDF2-SHA256, 100k iterations)
        // This hash is generated by our Pbkdf2PasswordHasher
        var adminId = "a0000000-0000-0000-0000-000000000001";
        var passwordHash = GeneratePasswordHash("Admin@123");

        Execute.Sql($@"
            INSERT INTO identity.users (id, email, password_hash, first_name, last_name, role, is_active, created_at, updated_at)
            VALUES (
                '{adminId}',
                'admin@luxora.com',
                '{passwordHash}',
                'Admin',
                'User',
                'Admin',
                TRUE,
                NOW(),
                NOW()
            )
            ON CONFLICT (email) DO NOTHING;
        ");
    }

    public override void Down()
    {
        Execute.Sql("DELETE FROM identity.users WHERE email = 'admin@luxora.com';");
    }

    private static string GeneratePasswordHash(string password)
    {
        var salt = new byte[16];
        // Use a fixed salt for the seed so it's reproducible
        var fixedSaltBytes = System.Text.Encoding.UTF8.GetBytes("LuxoraAdminSeed!");
        Array.Copy(fixedSaltBytes, salt, 16);

        var hash = System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(
            password,
            salt,
            100_000,
            System.Security.Cryptography.HashAlgorithmName.SHA256,
            32
        );

        return $"{Convert.ToBase64String(salt)}.{Convert.ToBase64String(hash)}";
    }
}
